<div class="row">
    <!-- Basic Form-->
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header border-bottom">
                <h3 class="h4 mb-0">Crear Informe</h3>
            </div>
            <div class="card-body">
                <form method="POST" action="<?= $_SERVER['PHP_SELF'] ?>">
                    <div class="mb-3">
                        <label class="form-label" for="desayuno">Desayuno</label>
                        <input class="form-control" id="desayuno" type="text" name="desayuno">

                    </div>
                    <button class="btn btn-primary" type="submit">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</div>