<div class="row">
    <div class="card">
        <div class="card-header border-bottom">
            <h3 class="h4 mb-0">Informes:</h3>
        </div>
        <div class="card-body">
            <?php if (empty($informes)) { ?>
            <div class="alert alert-primary d-flex align-items-center" role="alert">
                <i class="fa fa-info-circle fa-2x me-4"></i>
                <div>
                    No hay ningún informe actualmente.
                </div>
            </div>
            <?php } else { ?>
            <div class="table-responsive">
                <table class="table text-sm mb-0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Paciente</th>
                            <th scope="col">Celador</th>
                            <th scope="col">Dieta</th>
                            <th scope="col">Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($informes as $dato) { ?>

                        <tr>
                            <td><?= $dato['informe']->getId() ?></td>
                            <td><?= sprintf("%s %s", $dato['paciente']->getNombre(), $dato['paciente']->getApellidos()) ?>
                            </td>
                            <td><?= sprintf("%s %s", $dato['empleado']->getNombre(), $dato['empleado']->getApellidos()) ?>
                            </td>
                            <td><?= $dato['informe']->getDieta() ?></td>
                            <td><?= $dato['informe']->getFecha() ?></td>
                        </tr>

                        <?php } ?>

                    </tbody>
                </table>
            </div>
            <?php } ?>
        </div>
    </div>
</div>