<div class="row">
    <div class="card">
        <div class="card-header border-bottom d-flex">
            <div class="card-title">
                <h3 class="h4 mb-0">Informes:</h3>
            </div>
            <?php if (null !== $idPaciente) : ?>
            <div class="ms-auto"><a href="/informes/crear.php?idPaciente=<?= $idPaciente ?>" class="btn btn-primary"><i
                        class="fa fa-plus me-2"></i>Nuevo informe</a></div>
            <?php endif; ?>
        </div>
        <div class="card-header">

            <form class="row row-cols-lg-auto g-3 align-items-center" method="GET" action="/informes/index.php">
                <div class="col-12">
                    <label class="visually-hidden" for="ordenPor">Ordenar por</label>
                    <select class="form-select" id="ordenPor" name="ordenPor">
                        <option value="id"
                            <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'id' ? 'selected' : '') ?>>
                            Ordenar Por...
                        </option>
                        <option value="paciente"
                            <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'paciente' ? 'selected' : '') ?>>
                            Paciente</option>
                        <option value="empleado"
                            <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'empleado' ? 'selected' : '') ?>>
                            Empleado</option>
                        <option value="dieta"
                            <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'dieta' ? 'selected' : '') ?>>
                            Dieta</option>
                        <option value="fecha"
                            <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'fecha' ? 'selected' : '') ?>>
                            Fecha</option>
                    </select>
                </div>
                <div class="col-12">
                    <label class="visually-hidden" for="orden">Orden</label>
                    <select class="form-select" name="orden" id="orden">
                        <option value="ASC"
                            <?= (isset($busqueda['orden']) && $busqueda['orden'] === 'ASC' ? 'selected' : '') ?>>A - Z
                        </option>
                        <option value="DESC"
                            <?= (isset($busqueda['orden']) && $busqueda['orden'] === 'DESC' ? 'selected' : '') ?>>Z - A
                        </option>
                    </select>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary rounded-2">Actualizar</button>
                </div>
            </form>
        </div>
        <div class="card-body">
            <?php if (empty($resultado)) { ?>
            <div class="alert alert-primary d-flex align-items-center" role="alert">
                <i class="fa fa-info-circle fa-2x me-4"></i>
                <div>
                    No hay ningún informe actualmente.
                </div>
            </div>
            <?php } else { ?>
            <div class="table-responsive">
                <table class="table text-sm mb-0">
                    <thead>
                        <tr>
                            <th scope="col">Paciente</th>
                            <th scope="col">Empleado</th>
                            <th scope="col">Dieta</th>
                            <th scope="col">Fecha / Hora</th>
                            <th scope="col"></th>
                        </tr>

                    </thead>
                    <tbody>
                        <?php foreach ($resultado->getElementosActuales() as $informe) { ?>
                        <?php
                                if (ControlAcceso::tieneAcceso('INFORMES@VER_PROPIOS')) : ?>
                        <tr>
                            <td class="align-middle">
                                <?= sprintf("%s %s", $informe->getPaciente()->getNombre(), $informe->getPaciente()->getApellidos()) ?>
                            </td>
                            <td class="align-middle">
                                <?= sprintf("%s %s", $informe->getEmpleado()->getNombre(), $informe->getEmpleado()->getApellidos()) ?>
                            </td>
                            <td class="align-middle text-truncate" style="max-width: 30px;">
                                <?php if ($informe->getDieta() !== null) : ?>
                                <?= $informe->getDieta()->getNombre() ?>
                                <?php else : ?>
                                Sin asignar
                                <?php endif; ?>
                            </td>
                            <td class="align-middle"><?= $informe->getFecha()->format('d/m/Y H:i:s') ?></td>
                            <td class="align-middle"><a href="/informes/editar.php?idInforme=<?= $informe->getId() ?>"
                                    class="btn btn-primary rounded-circle"><i class="fa fa-pencil"></i></a></td>
                        </tr>
                        <?php endif; ?>

                        <?php } ?>

                    </tbody>
                </table>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col my-3">
        <?php $resultado->mostrarPaginador("informes"); ?>
    </div>
</div>