<!DOCTYPE html>
<html>

<?php require(__DIR__ . "/../../view/head.php"); ?>

<body>
    <div class="login-page d-flex align-items-center bg-gray-100">
        <div class="container mb-3">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-body p-5">
                            <header class="text-center mb-5">
                                <h1 class="text-xxl text-gray-400 text-uppercase">
                                    HOSPITALIS <strong class="text-primary">CONSULTING</strong>
                                </h1>
                                <p class="text-gray-500 fw-light">Introduce las credenciales de acceso.</p>
                            </header>
                            <form class="login-form" method="post" action="/login/login.php">
                                <div class="row">
                                    <div class="col-lg-7 mx-auto">
                                        <div class="input-material-group mb-3">
                                            <input class="input-material <?= (isset($loginErr) && !empty($loginErr) ? 'is-invalid' : '') ?>" id="username" type="text" name="username" autocomplete="off" required data-validate-field="username">
                                            <div class="invalid-feedback"><?= (isset($loginErr) && !empty($loginErr) ? $loginErr : '') ?></div>
                                            <label class="label-material" for="login-username">Usuario</label>
                                        </div>
                                        <div class="input-material-group mb-4">
                                            <input class="input-material <?= (isset($loginErr) && !empty($loginErr) ? 'is-invalid' : '') ?>" id="login-password" type="password" name="userPassword" required data-validate-field="userPassword">
                                            <div class="invalid-feedback"><?= (isset($loginErr) && !empty($loginErr) ? $loginErr : '') ?></div>
                                            <label class="label-material" for="login-password">Contraseña</label>
                                        </div>
                                    </div>
                                    <div class="col-12 text-center">
                                        <button class="btn btn-primary mb-3 rounded-pill" id="login" type="submit">Entrar</button>
                                        <br>
                                        <a class="text-xs text-paleBlue" href="/login/restablecer.php">
                                            ¿Has olvidado la contraseña?
                                        </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/vendor/choices.js/public/assets/scripts/choices.min.js"></script>
    <script src="/assets/vendor/just-validate/js/just-validate.min.js"></script>
    <script src="/assets/vendor/overlayscrollbars/js/OverlayScrollbars.min.js"></script>
    <script src="/assets/js/front.js"></script>
</body>

</html>