<!DOCTYPE html>
<html>

<?php require(__DIR__ . "/../../view/head.php"); ?>

<body>
    <div class="login-page d-flex align-items-center bg-gray-100">
        <div class="container mb-3">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-body p-5">
                            <header class="text-center mb-5">
                                <h1 class="text-xxl text-gray-400 text-uppercase">
                                    NO <strong class="text-primary">AUTORIZADO</strong>
                                </h1>
                            </header>
                            <div class="row">
                                <div class="col-12 text-center">
                                    <i class="fa fa-exclamation-triangle fa-4x text-danger mb-3"></i>
                                    <h3>Lo siento, pero no tienes acceso a este recurso.</h3>
                                    <a class="text-xs text-paleBlue" href="/index.php">
                                        Regresar a la página de indicio
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/vendor/overlayscrollbars/js/OverlayScrollbars.min.js"></script>
    <script src="/assets/js/front.js"></script>
</body>

</html>