<!DOCTYPE html>
<html>

<?php require(__DIR__ . "/../../view/head.php"); ?>

<body>
    <div class="login-page d-flex align-items-center bg-gray-100">
        <div class="container mb-3">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-body p-5">
                            <header class="text-center mb-5">
                                <h1 class="text-xxl text-gray-400 text-uppercase">
                                    Restablecer <strong class="text-primary">Contraseña</strong>
                                </h1>
                                <p class="text-gray-500 fw-light">Introduce la nueva contraseña.</p>
                            </header>
                            <form class="login-form" method="post" action="/login/restablecer.php">
                                <div class="row">
                                    <div class="col-lg-7 mx-auto">
                                        <div class="mb-3">
                                            <label class="form-label" for="DNI">Usuario</label>
                                            <input class="form-control <?= (isset($usuarioErr) && !empty($usuarioErr) ? 'is-invalid' : '') ?>" id="DNI" name="DNI" type="text">
                                            <div class="invalid-feedback"><?= (isset($usuarioErr) && !empty($usuarioErr) ? $usuarioErr : '') ?></div>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label" for="newPassword">Contraseña</label>
                                            <input class="form-control <?= (isset($newPasswordErr) && !empty($newPasswordErr) ? 'is-invalid' : '') ?>" id="newPassword" name="newPassword" type="password">
                                            <div class="invalid-feedback"><?= (isset($newPasswordErr) && !empty($newPasswordErr) ? $newPasswordErr : '') ?></div>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label" for="newConfirmPassword">Confirmar Contraseña</label>
                                            <input class="form-control" id="newConfirmPassword" name="newConfirmPassword" type="password">

                                        </div>
                                    </div>
                                    <div class="col-12 text-center">
                                        <button class="btn btn-primary mb-3 rounded-pill" id="restablecer" type="submit">Enviar</button>
                                        <br>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/vendor/choices.js/public/assets/scripts/choices.min.js"></script>
    <script src="/assets/vendor/just-validate/js/just-validate.min.js"></script>
    <script src="/assets/vendor/overlayscrollbars/js/OverlayScrollbars.min.js"></script>
    <script src="/assets/js/front.js"></script>
</body>

</html>