<!-- Basic Form-->
<form method="POST" action="/pacientes/editar.php?idPaciente=<?= $idPaciente ?>">
    <div class="row">
        <div class="card-group px-0 mb-3">
            <div class="card">
                <div class="card-header border-bottom">
                    <h3 class="h4 mb-0">Datos Paciente</h3>
                </div>
                <?php if ($paciente) : ?>
                <div class="card-body">
                    <p class="text-sm">Por favor, inserte los datos del paciente.</p>
                    <div class="row">
                        <div class="col-md-4 mb-3">
                            <label class="form-label" for="nombre"><i class="fa fa-user me-2"></i>Nombre</label>
                            <input class="form-control" id="nombre" value="<?= $paciente->getNombre() ?>" type="text"
                                name="nombre" aria-describedby="Nombre">
                        </div>
                        <div class="col-md-4 mb-3">
                            <label class="form-label" for="apellidos"><i class="fa fa-user me-2"></i>Apellidos</label>
                            <input class="form-control" id="apellidos" value="<?= $paciente->getApellidos() ?>"
                                name="apellidos" type="text">
                        </div>
                    </div>
                    <div class="row"></div>
                    <div class="row">
                        <div class="col-4 mb-3">
                            <label class="form-label" for="fechaNacimiento"><i class="fa fa-calendar me-2"></i>Fecha
                                nacimiento</label>
                            <input class="form-control" id="fechaNacimiento" name="fechaNacimiento" type="text"
                                value="<?= $paciente->getFechaNacimiento() ?>">
                        </div>
                        <div class="col-4 mb-3">
                            <label class="form-label" for="habitacion"><i class="fa fa-bed me-2"></i>Habitación</label>
                            <input class="form-control" id="habitacion" name="habitacion"
                                value="<?= $paciente->getHabitacion() ?>" type="text">
                        </div>
                        <div class="col-4 mb-3">
                            <label class="form-label" for="estado"><i class="fa fa-heart me-2"></i>Estado</label>
                            <select class="form-select" id="estado" name="estado">
                                <option value="-1">Estado del paciente...</option>
                                <?php foreach ($estados as $indice => $estado) { ?>
                                <option value="<?= $indice ?>"
                                    <?= ($paciente->getEstado() === (int)$indice ? 'selected' :  '') ?>>
                                    <?= ucfirst($estado) ?> </option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <input type="hidden" name="idPaciente" value="<?= $idPaciente ?>">
                    <button class="btn btn-primary" type="submit"><i class="fa fa-save me-2"></i>Guardar</button>
                </div>
            </div>
            <?php else : ?>
            <h3>No hay paciente</h3>
            <?php endif; ?>
        </div>
    </div>

    <?php
    require_once(__DIR__ . "/../../dietas/model/TablaDieta.php");
    $dietas = TablaDieta::getInstancia()->getDietas();
    $collapsable = true;
    require_once(__DIR__ . "/../../dietas/view/index.phtml");
    ?>


</form>