<!-- Basic Form-->
<form method="POST" action="/pacientes/crear.php">
    <div class="row">
        <div class="card-group px-0 mb-3">
            <div class="card">
                <div class="card-header border-bottom">
                    <h3 class="h4 mb-0">Datos Paciente</h3>
                </div>
                <div class="card-body">
                    <p class="text-sm">Por favor, inserte los datos del paciente.</p>
                    <div class="row">
                        <div class="col-md-4 mb-3">
                            <label class="form-label" for="nombre">Nombre</label>
                            <input class="form-control" id="nombre" value="<?= $paciente->getNombre() ?>" type="text" name="nombre" aria-describedby="Nombre">
                        </div>
                        <div class="col-md-4 mb-3">
                            <label class="form-label" for="apellidos">Apellidos</label>
                            <input class="form-control" id="apellidos" value="<?= $paciente->getApellidos() ?>" name="apellidos" type="text">
                        </div>
                    </div>
                    <div class="row"></div>
                    <div class="row">
                        <div class="col-4 mb-3">
                            <label class="form-label" for="habitacion">Habitación</label>
                            <input class="form-control" id="habitacion" name="habitacion" value="<?= $paciente->getHabitacion ?>" type="text">
                        </div>
                        <div class="col-4 mb-3">
                            <label class="form-label" for="estado">Estado</label>
                            <select class="form-select" id="estado" name="estado">
                                <option value="-1">Estado del paciente...</option>
                                <?php foreach ($estados as $indice => $estado) { ?>
                                    <option value="<?= $indice ?> <?= ($paciente->getEstado() === $estado ? 'selected' :  '') ?>"><?= ucfirst($estado) ?> </option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Enviar</button>
                </div>
            </div>
        </div>
    </div>

    <?php
    require_once(__DIR__ . "/../../dietas/model/TablaDieta.php");
    $tablaDietas = new TablaDieta();
    $dietas = $tablaDietas->getDietas();
    $collapsable = true;
    require_once(__DIR__ . "/../../dietas/view/index.phtml");
    ?>


</form>