<?php
require_once(__DIR__ . "/../../dietas/model/TablaDieta.php");
?>
<div class="row">
    <div class="card">
        <div class="card-header border-bottom">
            <h3 class="h4 mb-0">Listado pacientes:</h3>
        </div>
        <div class="card-body">
            <?php if (empty($pacientes)) : ?>
            <div class="alert alert-primary d-flex align-items-center" role="alert">
                <i class="fa fa-info-circle fa-2x me-4"></i>
                <div>
                    No hay ningún paciente registrado actualmente.
                </div>
            </div>
            <?php else : ?>
            <div class="table-responsive">
                <table class="table text-sm mb-0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellidos</th>
                            <th scope="col">Fecha nacimiento</th>
                            <th scope="col">Nº habitación</th>
                            <th scope="col">Dieta</th>
                            <th scope="col">Estado</th>
                            <th scope="col">Fecha de registro</th>
                            <th scope="col">Fecha de salida</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($pacientes as $paciente) : ?>

                        <tr>
                            <td class="align-middle"><?= $paciente->getId() ?></td>
                            <td class="align-middle"><?= $paciente->getNombre() ?></td>
                            <td class="align-middle"><?= $paciente->getApellidos() ?></td>
                            <td class="align-middle"><?= $paciente->getFechaNacimiento() ?></td>
                            <td class="align-middle"><?= $paciente->getHabitacion() ?></td>
                            <td class="align-middle">
                                <?php if ($paciente->getDieta()) : ?>
                                <?= $paciente->getDieta() ?>
                                <?php else : ?>
                                Sin asignar
                                <?php endif; ?>
                            </td>
                            <td class="align-middle"><?= $paciente->getEstado() ?></td>
                            <td class="align-middle"><?= $paciente->getFechaRegistro() ?></td>
                            <td class="align-middle"><?= $paciente->getFechaSalida() ?></td>
                            <td class="align-middle">
                                <a class="btn btn-primary rounded-circle align-middle"
                                    href="/pacientes/editar.php?idPaciente=<?= $paciente->getId(); ?>"><i
                                        class="fa fa-edit"></i></a>
                                <a class="btn btn-outline-primary rounded-circle"
                                    href="/informes/index.php?idPaciente=<?= $paciente->getId(); ?>"><i
                                        class="fa fa-file-text-o"></i></a>
                            </td>
                        </tr>

                        <?php endforeach; ?>

                    </tbody>
                </table>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>