<?php
require_once(__DIR__ . "/../../pacientes/model/Paciente.php");
?>
<div class="row">
    <div class="card">
        <div class="card-header border-bottom">
            <h3 class="h4 mb-0">Listado pacientes:</h3>
        </div>

        <div class="card-header">

            <form class="row row-cols-lg-auto g-3 align-items-center" method="GET" action="/pacientes/index.php">
                <div class="col-12">
                    <label class="visually-hidden" for="ordenPor">Ordenar por</label>
                    <select class="form-select" id="ordenPor" name="ordenPor">
                        <option value="id" <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'id' ? 'selected' : '') ?>>
                            Ordenar Por...
                        </option>
                        <option value="nombre" <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'nombre' ? 'selected' : '') ?>>
                            Nombre</option>
                        <option value="apellidos" <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'apellidos' ? 'selected' : '') ?>>
                            Apellidos</option>
                        <option value="estado" <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'estado' ? 'selected' : '') ?>>
                            Estado</option>
                        <option value="dieta" <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'dieta' ? 'selected' : '') ?>>
                            Dieta</option>
                        <option value="fecha" <?= (isset($busqueda['ordenPor']) && $busqueda['ordenPor'] === 'fecha' ? 'selected' : '') ?>>
                            Fecha</option>
                    </select>
                </div>
                <div class="col-12">
                    <label class="visually-hidden" for="orden">Orden</label>
                    <select class="form-select" name="orden" id="orden">
                        <option value="ASC" <?= (isset($busqueda['orden']) && $busqueda['orden'] === 'ASC' ? 'selected' : '') ?>>A - Z
                        </option>
                        <option value="DESC" <?= (isset($busqueda['orden']) && $busqueda['orden'] === 'DESC' ? 'selected' : '') ?>>Z - A
                        </option>
                    </select>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary rounded-2">Actualizar</button>
                </div>
            </form>
        </div>
        <div class="card-body">
            <?php if (empty($pacientes)) : ?>
                <div class="alert alert-primary d-flex align-items-center" role="alert">
                    <i class="fa fa-info-circle fa-2x me-4"></i>
                    <div>
                        No hay ningún paciente registrado actualmente.
                    </div>
                </div>
            <?php else : ?>
            <div class="table-responsive">
                <table class="table text-sm mb-0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellidos</th>
                            <th scope="col">Fecha nacimiento</th>
                            <th scope="col"><i class="fa fa-bed"></i></th>
                            <th scope="col">Dieta</th>
                            <th scope="col">Estado</th>
                            <th scope="col">Fecha de registro</th>
                            <th scope="col">Fecha de salida</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($pacientes->getElementosActuales() as $paciente) : ?>

                        <tr>
                            <td class="align-middle"><?= $paciente->getId() ?></td>
                            <td class="align-middle"><?= $paciente->getNombre() ?></td>
                            <td class="align-middle"><?= $paciente->getApellidos() ?></td>
                            <td class="align-middle"><?= $paciente->getFechaNacimiento() ?></td>
                            <td class="align-middle"><?= $paciente->getHabitacion() ?></td>
                            <td class="align-middle text-truncate" style="max-width: 40px;">
                                <?php if ($paciente->getDieta()) : ?>
                                <?= $paciente->getDieta() ?>
                                <?php else : ?>
                                Sin asignar
                                <?php endif; ?>
                            </td>
                            <td class="align-middle"><?= Paciente::getNombreEstado($paciente->getEstado()) ?></td>
                            <td class="align-middle"><?= $paciente->getFechaRegistro() ?></td>
                            <td class="align-middle"><?= $paciente->getFechaSalida() ?></td>
                            <td class="align-middle">
                                <?php
                                        if (ControlAcceso::tieneAcceso('PACIENTES@EDITAR')) : ?>
                                <a class="btn btn-primary btn-sm rounded-circle align-middle mb-md-2"
                                    href="/pacientes/editar.php?idPaciente=<?= $paciente->getId(); ?>"><i
                                        class="fa fa-edit"></i></a>
                                <?php endif; ?>
                                <a class="btn btn-outline-primary btn-sm rounded-circle"
                                    href="/informes/index.php?idPaciente=<?= $paciente->getId(); ?>"><i
                                        class="fa fa-file-text-o"></i></a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php if ($pacientes instanceof Paginador) : ?>
    <div class="row">
        <div class="col my-3">
            <?php $pacientes->mostrarPaginador("pacientes"); ?>
        </div>
    </div>
<?php endif; ?>