<div class="row">
    <div class="card">
        <div class="card-header border-bottom d-flex " style="
  position: -webkit-sticky;
  position: sticky;
  top: 0;">
            <div class="">
                <h3 class="h4 text-uppercase mb-0">Tabla de dietas:</h3>
            </div>
            <div class="ms-auto">

                <?php if (isset($collapsable)) { ?>
                <button class="btn btn-primary ms-auto" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseTabla" aria-expanded="false" aria-controls="collapseTabla"
                    id="botonDietaCambiarVista">
                    Ver
                </button>

                <?php
                    require_once __DIR__ . "/../../view/service/InyectorScript.php";

                    $script = "<script>
                        (function(){
                            var tablaDietaColapsada = true;

                            var botonDietaCambiarVista = document.getElementById('botonDietaCambiarVista');

                            if (botonDietaCambiarVista) {
                                botonDietaCambiarVista.addEventListener('click', function() {
                                    tablaDietaColapsada = !tablaDietaColapsada;

                                    if (tablaDietaColapsada) {
                                        botonDietaCambiarVista.innerText = 'Ver';
                                    }
                                    else {
                                        botonDietaCambiarVista.innerText = 'Ocultar';
                                    }
                                });
                            }
                        })();
                    </script>";

                    InyectorScript::getInstancia()->agregarScript($script);
                    ?>
                <?php } ?>
            </div>
        </div>
        <div class="card-body <?= (isset($collapsable) ? 'collapse' : '') ?>" id="collapseTabla">
            <?php if (empty($dietas)) { ?>
            <div class="alert alert-primary d-flex align-items-center" role="alert">
                <i class="fa fa-info-circle fa-2x me-4"></i>
                <div>
                    No hay ninguna dieta disponible.
                </div>
            </div>
            <?php } else { ?>
            <div class="table-responsive">
                <table class="table text-sm mb-0">
                    <thead>
                        <tr>
                            <th scope="col">Categoría madre</th>
                            <th scope="col">Hijas 1</th>
                            <th scope="col">Hijas 2</th>
                            <?php if (isset($collapsable)) { ?>
                            <th scope="col" style="width: 3rem;"></th>
                            <?php } ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            foreach ($dietas as $dieta) {
                                if (empty($dieta->getHijas())) {
                                    imprimirDietaSinHijas($dieta);
                                } else {
                                    imprimirDietaConHijas($dieta);
                                }
                            }
                            ?>
                    </tbody>
                </table>
            </div>
            <?php } ?>
        </div>
    </div>
</div>
<?php return; ?>