<div class="row">
    <div class="card">
        <div class="card-header border-bottom">
            <h3 class="h4 mb-0">Tablal de dietas:</h3>
        </div>
        <div class="card-body">
            <?php if (empty($dietas['datos_dietas'])) { ?>
            <div class="alert alert-primary d-flex align-items-center" role="alert">
                <i class="fa fa-info-circle fa-2x me-4"></i>
                <div>
                    No hay ninguna dieta disponible.
                </div>
            </div>
            <?php } else { ?>
            <div class="table-responsive">
                <table class="table table-striped text-sm mb-0">
                    <thead>
                        <tr>
                            <th scope="col">Categoría madre</th>
                            <th scope="col">Hijas 1</th>
                            <th scope="col">Hijas 2</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                        </tr>

                    </tbody>
                </table>
            </div>
            <?php } ?>
        </div>
    </div>
</div>