<div class="row">
    <div class="card">
        <div class="card-header border-bottom">
            <h3 class="h4 mb-0">Listado empleados:</h3>
        </div>
        <div class="card-body">
            <?php if ($elementos->getNumeroTotalElementos() === 0) { ?>
            <div class="alert alert-primary d-flex align-items-center" role="alert">
                <i class="fa fa-info-circle fa-2x me-4"></i>
                <div>
                    No hay ningún empleado registrado actualmente.
                </div>
            </div>
            <?php } else { ?>
            <div class="table-responsive">
                <table class="table text-sm mb-0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellidos</th>
                            <th scope="col">DNI</th>
                            <th scope="col">Cargo</th>
                            <th scope="col"></th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($elementos->getElementosActuales() as $empleado) { ?>

                        <tr>
                            <td><?= $empleado->getId() ?></td>
                            <td><?= $empleado->getNombre() ?></td>
                            <td><?= $empleado->getApellidos() ?></td>
                            <td><?= $empleado->getDNI() ?></td>
                            <td><?= ucfirst($empleado->getNombreCargo()) ?></td>
                            <td>
                                <?php

                                        require_once(__DIR__ . "/../../login/services/ControlAcceso.php");
                                        if (ControlAcceso::tieneAcceso('EMPLEADOS@EDITAR')) : ?>
                                <a class="btn btn-primary"
                                    href="/empleados/editar.php?idEmpleado=<?= $empleado->getId() ?>"
                                    role="button">Editar</a>
                                <?php endif; ?>
                            </td>

                        </tr>

                        <?php } ?>

                    </tbody>
                </table>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col my-3">
        <?php $elementos->mostrarPaginador("empleados"); ?>
    </div>
</div>