<!DOCTYPE html>
<html lang="es">
<?php require(__DIR__ . "/head.php"); ?>



<body>

    <div class="page">
        <section class="pb-5">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 text-center">
                        <h1 class="text-danger">ERROR 404</h1>
                        <h3>Los sentimos, pero los Tusken se han llevado el elemento que buscas, vuelve a intentarlo más
                            tarde, tal vez ahayamos podido recuperarlo.</h3>
                        <p>Vuelve a la página de inicio o ponte en contacto con nosotros</p>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>

</html>