<!DOCTYPE html>
<html lang="es">
<?php require(__DIR__ . "/head.php"); ?>


<body>
    <?php require(__DIR__ . "/sidebar.php"); ?>

    <div class="page" id="docToPdf">
        <?php require(__DIR__ . "/header.php"); ?>
        <?php require(__DIR__ . "/breadcrumb.php"); ?>

        <button class="btn btn-primary" id="btnToPdf"><i class="fa fa-print"></i></button>
        <section class="pt-5">
            <div class="container-fluid">
                <!-- Contenido de la página -->
                <?php if (isset($contenido)) {
                    require($contenido);
                } ?>
            </div>
        </section>
        <?php require(__DIR__ . "/footer.php"); ?>

    </div>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/vendor/choices.js/public/assets/scripts/choices.min.js"></script>
    <script src="/assets/vendor/overlayscrollbars/js/OverlayScrollbars.min.js"></script>
    <script src="/assets/js/front.js"></script>
    <?php
    require_once(__DIR__ . "/service/InyectorScript.php");
    // Inyectamos los posibles scripts que se hayan agregado durante la ejecución de la aplicación.
    InyectorScript::getInstancia()->inyectarScripts();
    ?>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/canvg/3.0.9/umd.js"
        integrity="sha512-Wu9XXg78PiNE0DI4Z80lFKlEpLq7yGjquc0I35Nz+sYmSs4/oNHaSW8ACStXBoXciqwTLnSINqToeWP3iNDGmQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.5.0-beta4/html2canvas.min.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.0.272/jspdf.min.js">
    </script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/canvg/1.4.0/canvg.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script>
    $('#btnToPdf').click(() => {
        var pdf = new jsPDF('landscape', 'pt', 'a4');
        var output = document.getElementById('docToPdf')
        pdf.addHTML(output, function() {
            pdf.save('web.pdf');
        });
    })
    </script>
</body>

</html>